Table remfo.auth_user{
  id uuid [pk]
}

Table remfo.card{
  id uuid [pk]
  front text [not null]
  back text [not null]
  user_id uuid [not null]
  easiness real [not null, default:2.5]
  interval smallint [not null, default:0]
  repetitions smallint [not null, default:0]
  next_practice timestamptz  [not null, default: `now()`]
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz [not null, default: `now()`]
  indexes {
    next_practice
  }
}

ref: remfo.auth_user.id-remfo.card.user_id